XI-58842 initial set-up for the ng-masterdata repo
xpologistics/intermodal-ng-masterdata pull request #1
Opened 2022-01-24 15:33 UTC by rkumar014

2022-01-24 19:09 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/masterdata/masterdata.routing.module.ts
> +    path: '',
Here we will have to give the path for vendor component.

2022-01-24 19:13 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/service/services/base.service.ts
> +
Set the url for workorder API here

2022-01-24 19:19 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/xpoim-masterdata.module.ts
> +    MasterdataComponent,
Do not import the components here. Create a routing module and add it in module. In the routing module, based on the path load the module.

2022-01-24 19:21 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/xpoim-masterdata.service.ts
> +import { Injectable } from '@angular/core';
This file is not needed

2022-01-24 19:31 UTC, xvnambiar commented on intermodal-ng-masterdata/src/app/app.component.html
> +<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
Clear the content of this file

2022-01-24 19:34 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/package.json
> +  "name": "xpoim-masterdata",
Please check if some commands need to be added

2022-01-24 19:35 UTC, xvnambiar commented on intermodal-ng-masterdata/tsconfig.json
> +{
check for prefix

2022-01-25 13:16 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/masterdata/masterdata.component.html
> +<p>masterdata works!</p>
Please remove this

2022-01-25 16:48 UTC, xvvijay requested changes
Please see inline comments

2022-01-27 08:34 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/masterdata/masterdata.routing.module.ts
> +    path: 'vendorCompliance',
route should be like vendor-compliance

2022-01-27 08:38 UTC, xvnambiar commented on intermodal-ng-masterdata/projects/xpoim-masterdata/src/lib/xpoim-masterdata.module.ts
> +       VendorComplianceComponent
vendor compliancecomponent, no need to add here.it has to be lazy loaded

2022-01-27 10:57 UTC, xvnambiar approved these changes

2022-01-27 11:14 UTC, xvvijay approved these changes

2022-01-27 11:18 UTC, merged